# Generated by Django 4.0.3 on 2024-10-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_about_user_adress_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('number', models.IntegerField()),
                ('price', models.CharField(blank=True, max_length=300)),
                ('img', models.CharField(blank=True, max_length=500)),
                ('adress', models.CharField(blank=True, max_length=500)),
                ('Description', models.TextField(blank=True)),
                ('facilities', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ECO', 'Эконом'), ('SND', 'Стандарт'), ('PRE', 'Премиум'), ('LUX', 'Люкс'), ('KIN', 'Президентский')], max_length=3)),
                ('beds', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
